# Lid settings
bindl=,switch:on:Lid Switch,exec,~/omarchy-supplement/scripts/lid.sh close
bindl=,switch:off:Lid Switch,exec,~/omarchy-supplement/scripts/lid.sh open

# Scale settings
monitor=,preferred,auto,1

# Mouse settings
input {
  sensitivity = 0
  force_no_accel = true
  touchpad {
    natural_scroll = true
  }
}

# Mount remote to local (OneDrive)
exec-once = rclone --vfs-cache-mode writes mount OneDrive: ~/OneDrive &