# Lid settings
bindl=,switch:on:Lid Switch,exec,~/.config/hypr/scripts/lid.sh close
bindl=,switch:off:Lid Switch,exec,~/.config/hypr/scripts/lid.sh open

# Scale settings
monitor=,preferred,auto,1

# Mouse settings
input {
  sensitivity = 0
  force_no_accel = true
}
