# Lid settings
bindl=,switch:on:Lid Switch,exec,~/.config/hypr/scripts/lid.sh close
bindl=,switch:off:Lid Switch,exec,~/.config/hypr/scripts/lid.sh open

# Mouse settings
input {
  senstivity = 0
  force_no_accel = true
}
